name: Delete Old Uploads

on:
  schedule:
    - cron: '0 * * * *' # Запускается каждый час

jobs:
  delete_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3

      - name: Удаление старых файлов
        run: |
          find uploads -type f -mmin +1440 -delete # Удаляет файлы старше 1440 минут (24 часа)

      - name: Коммит изменений (если есть)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Автоматическое удаление старых файлов"
          file_pattern: uploads/*
          branch: main # Коммитит в main ветку
          
